name: Lua Syntax Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lua_syntax_check:
    name: Check Lua Syntax
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Install Lua and LuaRocks
      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks

      # Install Luacheck locally
      - name: Install Luacheck locally
        run: |
          luarocks --local install luacheck
          # Ensure local bin directory is in the PATH
          echo 'export PATH=$HOME/.luarocks/bin:$PATH' >> $GITHUB_ENV

      # Get list of modified Lua files
      - name: Get list of modified Lua files
        id: modified_files
        run: |
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.lua')
          echo "::set-output name=files::$MODIFIED_FILES"

      # Run Luacheck on modified files and output to a log file
      - name: Run Luacheck
        if: steps.modified_files.outputs.files != ''
        run: |
          echo "${{ steps.modified_files.outputs.files }}" | xargs $HOME/.luarocks/bin/luacheck > luacheck.log || true

      # Annotate PR with results
      - name: Post Luacheck results
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('luacheck.log', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Luacheck results\n\`\`\`text\n${output}\n\`\`\``
            })
